myapp/urls.py
from django.urls import path
from myapp import views
app_name = 'myapp'

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('', views.base, name = "base1"),
    path('child1/', views.child1, name = "child11"),
    path('child2/', views.child2, name = "child22"),
    path('form/', views.form, name = "form"),


]

template_inheritance/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls")),
]

myapp/models.py
from django.db import models

# Create your models here.

myapp/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
    return render(request, "base.html")

def child1(request):
    return render(request, "child1.html")

def child2(request):
    return render(request, "child2.html")

def form(request):
    print(request.POST)
    return render(request, "form.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
    <title>Base Page</title>
    {% endblock %}
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

</head>
<body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active" href="{% url 'myapp:base1' %}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="{% url 'myapp:child11' %}">Child1</a>
            <a class="nav-item nav-link" href="{% url 'myapp:child22' %}">Child2</a>
            <a class="nav-item nav-link" href="{% url 'myapp:form' %}">Form</a>
          </div>
        </div>
      </nav>                                                              
    </div>

     
      {% block body_block %}
 
         <div class="container">
          <div class="jumbotron">
            <h1>Welcome to Home Page</h1>
        </div>
         </div>
      
      {% endblock body_block %}

      


</body>
</html>

templates/child1.html
{% extends "base.html" %}

{% block title %}
    <title>Child1 Page</title>
{% endblock %}

{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Welcome to Child1 page</h1>
    </div>

</div>   

{% endblock body_block %}

templates/child2.html
{% extends "base.html" %}

{% block title %}
    <title>Child2 Page</title>
{% endblock %}


{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h1>Welcome to Child2 page</h1>
    </div> 
</div>  

{% endblock body_block %}

templates/form.html
{% extends "base.html" %}

{% block body_block %}
  <div class="container">
    <h1 class="jumbotron">
      Welcome to Form Page
    </h1>
  
    <div class="container">
      <form method="POST">
        {% csrf_token %}
        <label for="Firstname"> <strong>FIRSTNAME</strong> :
          <input type="text" name="firstname" id="fname">
          <input class="btn btn-primary" type="submit" value="Submit">
        </label>
      </form>
    </div>
  </div>
{% endblock body_block %}